### ISSUE TITLE
Edit this page button is broken

### ISSUE THREAD

**Issue by 524119574** [dr497/serum-academy#3]
When I click the `Edit this page` button:
![image](https://user-images.githubusercontent.com/9982417/91634621-8ff3e900-e9e9-11ea-963e-988292ca4f39.png)

It shows it leads me to [here](https://github.com/dr497/serum-academyserum-dex/trade/_index.en.md)

**Comment by dr497** [comment]
Fixed! Thanks for the catch! 😃
